# Copyright © Michal Čihař <michal@deepsquads.org>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/DeepsquadsOrg/meta/

name: Pull request automation

on:
  pull_request_target:
    types: opened

permissions:
  contents: read

jobs:
  deepsquads_automerge:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    name: Deepsquads automerge
    if: github.actor == 'deepsquads'
    steps:
    - uses: peter-evans/enable-pull-request-automerge@v3
      with:
        pull-request-number: ${{ github.event.pull_request.number }}
        merge-method: rebase
